### PR TITLE
Pull updates from original repo [T1888]

### PR DESCRIPTION
**Pull request by Lagovas**
Pull updates from original repo due to broken io-console dependency which wasn't pinned to any version and we don't know which was used before. Plus updated our dockerfile which extends the original.
This update need for our engineering demo

### CODE REVIEW

**Comment by vixentael** [comment]
that's a huge PR, luckily this repo is just an demo example

**Comment by Lagovas** [comment]
actually it just 
```
git remote add source_repo https://github.com/rubygems/rubygems.org
git merge source_repo/master
```
And I added only one commit: https://github.com/cossacklabs/rubygems.org/pull/5/commits/497ec921527836e290b29f88392dc3ede9406e1c

So need to review only my last commit)

**Review by vixentael — APPROVED** [review]

**Comment by vixentael** [comment]
I am a bit concerned that most tests are red. Do we care here?

**Comment by Lagovas** [comment]
I checked... We don't pass linter (which wants double-quoted strings instead of one quote in our imports. it's not important for our demo IMHO), unit tests (which manipulates with ORM models which we touched and return encrypted data without `connector` which not used in unit-tests) and docker build script (which should be updated too to install the required version of  themis 0.10.0 and anyway he will fail because try to push at end)

**Pull request merged**
